export const trendingData = [
  {
    id: "1",
    title: "'The Witcher' Returns This Summer",
    content: "Watch the Season 3 Teaser",
    poster:
      "https://www.themoviedb.org/t/p/original/FdsAB1Z1IbECvvPu4JMkS0eQTY.jpg",
    link: "https://www.youtube.com/embed/EUlC8ue8NFI?autoplay=1",
    bgImage:
      "https://www.themoviedb.org/t/p/original/udwyPqbwWlpqvMgfbRemOahzc7z.jpg",
    duration: "1:12",
    url: "the witcher season 3",
    pageTitle: "The Witcher — Official Season 3 Teaser — Cineplex",
    name: "The Witcher",
    year: "2019",
    type: "Action, Adventure, SF, Fantasy, Drama",
    score: "8.2",
    description: "The Witcher Official Season 3 Teaser",
    plot: "Based on the fantasy bestseller of the same name, The Witcher is a story of destiny and family. Geralt of Rivia, a lone monster hunter, struggles to find his place in a world where humans sometimes prove to be worse than beasts. He meets a powerful witch and a young princess with a dangerous secret, and together they must learn to navigate the changing world of the Continent.",
  },
  {
    id: "2",
    title: "Magic Is Real in 'Wish'",
    content: "Watch the New Disney Trailer",
    poster:
      "https://www.themoviedb.org/t/p/original/fX6aprnTi7CIRySGp9PyGixiiLD.jpg",
    link: "https://www.youtube.com/embed/v8w6F5g-_E0?autoplay=1",
    bgImage:
      "https://www.themoviedb.org/t/p/original/mEcCz4Nzw57wJIXo6g69q9NUQih.jpg",
    duration: "2:02",
    url: "disney wish trailer",
    pageTitle: "Wish Official Trailer — Cineplex",
    name: "Wish",
    year: "2023",
    type: "Animation, Comedy, Family, Fantasy",
    score: "Not Rated",
    description: "Official Wish Trailer",
    plot: "Wish will follow a young girl named Asha who wishes on a star and gets a more direct answer than she bargained for when a trouble-making star comes down from the sky to join her.",
  },
  {
    id: "3",
    title: "'Next Goal Wins'",
    content: "Watch the Trailer",
    poster:
      "https://www.themoviedb.org/t/p/original/z0uigCKep9y2m6fWvcMJZq4FBNs.jpg",
    link: "https://www.youtube.com/embed/pRH5u5lpArQ?autoplay=1",
    bgImage:
      "https://www.themoviedb.org/t/p/original/9Kqmgc95pgT9khJJsfgRa4QtBzI.jpg",
    duration: "2:11",
    url: "next goal wins trailer",
    pageTitle: "Next Goal Wins Official Trailer — Cineplex",
    name: "Next Goal Wins",
    year: "2023",
    type: "Drama, Comedy, Sport",
    score: "Not Rated",
    description: "Official Next Goal Wins Trailer",
    plot: "The story of the infamously terrible American Samoa soccer team, known for a brutal 2001 FIFA match they lost 31-0.",
  },
  {
    id: "4",
    title: "Netflix Reveals 'Heartstopper' Season 2 Date",
    content: "Watch the Announcement",
    poster:
      "https://www.themoviedb.org/t/p/original/AhIQNMBrN2YsbmcdAtiHDswbVtH.jpg",
    link: "https://www.youtube.com/embed/ND5dVS7ETL8?autoplay=1",
    bgImage:
      "https://www.themoviedb.org/t/p/original/p3cAHHwyTJJoQlCtgYwb31t6rOq.jpg",
    duration: "1:09",
    url: "hearstopper season 2 release",
    pageTitle: "Heartstopper — Official Season 2 Release — Cineplex",
    name: "Heartstopper",
    year: "2022",
    type: "Drama, Romance",
    score: "8.7",
    description: "Heartstopper Official Season 2 Release Date",
    plot: "Teens Charlie and Nick discover their unlikely friendship might be something more as they navigate school and young love in this coming-of-age series.",
  },
  {
    id: "5",
    title: "Worlds Collide in 'The Flash'",
    content: "Watch the Trailer",
    poster:
      "https://www.themoviedb.org/t/p/original/mqx6Z5pSVtpWLOXAYFKx5rVKktb.jpg",
    link: "https://www.youtube.com/embed/hebWYacbdvc?autoplay=1",
    bgImage:
      "https://www.themoviedb.org/t/p/original/aaxyTDpFyjFTVlBUssKUkXdhPEO.jpg",
    duration: "2:57",
    url: "the flash 2023 trailer",
    pageTitle: "The Flash Official Trailer — Cineplex",
    name: "The Flash",
    year: "2023",
    type: "Action, Adventure, SF, Fantasy",
    score: "Not Rated",
    description: "Official The Flash Trailer",
    plot: "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
  },
  {
    id: "6",
    title: "'A Haunting in Venice'",
    content: "Watch the Teaser Trailer",
    poster:
      "https://www.themoviedb.org/t/p/original/wmXnuuP0EHG01pKRwUZy2weHLtw.jpg",
    link: "https://www.youtube.com/embed/rd620tOd6WE?autoplay=1",
    bgImage:
      "https://www.themoviedb.org/t/p/original/7C0xeAUYGQa0ETvPYndlaml9Y8H.jpg",
    duration: "2:04",
    url: "a haunting in venice trailer",
    pageTitle: "A Haunting in Venice — Cineplex",
    name: "A Haunting in Venice",
    year: "2023",
    type: "Crime, Horror, Mystery, Drama",
    score: "Not Rated",
    description: "Official A Haunting in Venice Teaser Trailer",
    plot: "Celebrated sleuth Hercule Poirot, now retired and living in self-imposed exile in Venice, reluctantly attends a Halloween séance at a decaying, haunted palazzo. When one of the guests is murdered, the detective is thrust into a sinister world of shadows and secrets.",
  },
];
